spring:
  application:
    name: taco-cloud
  boot:
    admin:
      client:
        url: http://localhost:8000

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/taco-cloud
    username: postgres
    password: postgres
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://localhost:8090/oauth2/jwks
  kafka:
    bootstrap-server: localhost:9092

  flyway:
    url: jdbc:postgresql://localhost:5432/taco-cloud
    user: postgres
    password: postgres

cors:
  origin:
    patterns: http://localhost*

taco:
  page-size: 10
  order:
    page-size: 10

management:
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED
  endpoints:
    web:
      exposure:
        include: '*'